spring.application.name=customer-service
server.port=8081
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:9999}
#LOG
logging.file.name=logs/customer-service.log
logging.file.path=logs
logging.level.root=INFO