spring.application.name=gateway.service
server.port=9999
eureka.instance..prefer-id-address=true
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
#LOG
logging.file.name=logs/gateway-service.log
logging.file.path=logs
logging.level.root=INFO